services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    ports:
      - "5432:5432"

  reservation-service:
    image: lab2-reservation-service:local
    build:
      context: ./reservation-service
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://program:test@postgres:5432/reservations?sslmode=disable"
    ports:
      - "8070:8070"
    depends_on:
      postgres:
        condition: service_healthy

  gateway-service:
    image: lab2-gateway-service:local
    build:
      context: ./gateway-service
    restart: on-failure
    environment:
      RESERVATION_SERVICE_URL: "http://reservation-service:8070"
    ports:
      - "8080:8080"
    depends_on:
      reservation-service:
        condition: service_started

  payment-service:
    image: lab2-payment-service:local
    build:
      context: ./payment-service
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://program:test@postgres:5432/payments?sslmode=disable"
    ports:
      - "8060:8060"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data: